### ISSUE TITLE
目前谷歌云搭的梯子不出两小时就被封，求如何破解

### ISSUE THREAD

**Issue by fandayrockworld** [loremwalker/fq-book#12]
目前谷歌云搭的梯子不出两小时就被封，求如何破解

**Comment by loremwalker** [comment]
破解怎么可能，尽量避免被侦测；端口号、搭建平台、v2Ray、流量是否大量进出国内主流网站，往这几个方面考虑。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fandayrockworld** [comment]
能给个最安全的方式不，我就拿下面这俩镜像搭的，不知道还能不能改进呢，这封的也太快了。。
```
version: '3'
services:
    shadowsocks:
        container_name: shadowsocks
        image: gists/shadowsocks-libev
        ports:
            - "12346:8388/udp"
        networks:
            overlay:
        environment:
          - PASSWORD=bnsbdl000
          - METHOD=chacha20-ietf-poly1305
        restart: always
    simple-obfs:
        container_name: obfs
        image: gists/simple-obfs
        ports:
            - "12346:8388/tcp"
        environment:
            - FORWARD=shadowsocks:8388
        depends_on:
            - shadowsocks
        networks:
            overlay:
        restart: always
networks:
    overlay:
        driver: bridge

```
